channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.2
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==2.1.3
  - pandas==2.3.3
  - psutil==7.1.0
  - scikit-learn==1.5.2
  - scipy==1.15.3
  - xgboost==2.1.2
name: mlflow-env
