data:
  raw_path: "data/raw/customer_churn.json"
  profile_report: "data/processed/profile.html"

  processed_path: "data/processed/churn_clean.parquet"
  labeled_path: "data/processed/churn_labels.parquet"

  features_path: "data/processed/churn_features.parquet"
  predictions_path: "data/predictions/churn_predictions.parquet"


report:
  folder: reports

tables:
  path: "data/monitoring/predictions.db"
  prediction_table: predictions

model:
  type: "xgboost"
  test_size: 0.2
  random_state: 42

api:
  host: "0.0.0.0"
  port: 8000

window:
  feature_days: 31    # length of feature window in days
  target_days: 31       # length of target window in days
